import { type RecipeResponse } from "@shared/routes";
import { format } from "date-fns";
import { Printer, Copy, Check, FileText } from "lucide-react";
import { Button } from "@/components/ui/button";
import { useState } from "react";
import { motion } from "framer-motion";

interface RecipeCardProps {
  recipe: RecipeResponse;
  variant?: "full" | "compact";
}

export function RecipeCard({ recipe, variant = "full" }: RecipeCardProps) {
  const [copied, setCopied] = useState(false);

  const handlePrint = () => {
    window.print();
  };

  const handleCopyId = () => {
    navigator.clipboard.writeText(recipe.publicId);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  if (variant === "compact") {
    return (
      <motion.div 
        initial={{ opacity: 0, y: 10 }}
        animate={{ opacity: 1, y: 0 }}
        className="bg-card rounded-xl border border-border p-4 shadow-sm hover:shadow-md transition-shadow group"
      >
        <div className="flex items-start justify-between mb-3">
          <div className="bg-primary/5 text-primary px-2.5 py-1 rounded-md text-xs font-mono font-medium border border-primary/10">
            #{recipe.publicId}
          </div>
          <span className="text-xs text-muted-foreground">
            {format(new Date(recipe.createdAt || new Date()), "MMM d, yyyy")}
          </span>
        </div>
        <h3 className="font-semibold text-foreground mb-1 truncate">{recipe.fill}</h3>
        <p className="text-sm text-muted-foreground line-clamp-2">{recipe.info}</p>
      </motion.div>
    );
  }

  return (
    <motion.div 
      initial={{ opacity: 0, scale: 0.95 }}
      animate={{ opacity: 1, scale: 1 }}
      className="bg-card rounded-2xl border border-border shadow-xl overflow-hidden print:shadow-none print:border-none"
    >
      <div className="bg-muted/30 border-b border-border p-6 flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <span className="bg-primary/10 text-primary px-3 py-1 rounded-full text-xs font-bold tracking-wide uppercase">
              Order ID
            </span>
            <span className="text-xs text-muted-foreground font-medium">
              Generated on {format(new Date(recipe.createdAt || new Date()), "MMMM d, yyyy 'at' h:mm a")}
            </span>
          </div>
          <div className="flex items-center gap-3">
            <h2 className="text-3xl font-mono font-bold text-foreground tracking-tight">
              {recipe.publicId}
            </h2>
            <button 
              onClick={handleCopyId}
              className="text-muted-foreground hover:text-primary transition-colors p-1"
              title="Copy ID"
            >
              {copied ? <Check className="w-5 h-5 text-green-500" /> : <Copy className="h-5 w-5" />}
            </button>
          </div>
        </div>

        <Button onClick={handlePrint} variant="outline" className="print:hidden gap-2 border-border hover:bg-card hover:text-primary hover:border-primary/30 shadow-sm">
          <Printer className="w-4 h-4" />
          Print Recipe
        </Button>
      </div>

      <div className="p-8 space-y-8">
        <div>
          <h3 className="text-sm uppercase tracking-wider text-muted-foreground font-semibold mb-3 flex items-center gap-2">
            <FileText className="w-4 h-4" />
            Fill Details
          </h3>
          <div className="bg-muted/50 rounded-xl p-4 border border-border text-lg text-foreground font-medium">
            {recipe.fill}
          </div>
        </div>

        <div>
          <h3 className="text-sm uppercase tracking-wider text-muted-foreground font-semibold mb-3">
            Additional Information
          </h3>
          <div className="prose dark:prose-invert max-w-none text-muted-foreground">
            <p className="whitespace-pre-wrap leading-relaxed">{recipe.info}</p>
          </div>
        </div>
      </div>
      
      <div className="bg-muted/50 p-4 border-t border-border text-center text-xs text-muted-foreground print:block hidden">
        Generated by Alon Hosting PH Recipe Generator • {window.location.href}
      </div>
    </motion.div>
  );
}
